#Config 1.0 for GoatHornCannon plugin by:
#moikheck
#Golem_Leader
#Michael Heckman
#(All of the above are the same person)

#Understanding the config:
#There are two types of horns: normal and admin. For every setting, there is an option for both.

#Determines whether permissions are used for the plugin
#Permission Names: 
#goathorncannon.use
#goathorncannon.admin.use
#goathorncannon.craft
#goathorncannon.admin.craft
#goathorncannon.command
#goathorncannon.admin.command
#goathorncannon.command.others
#goathorncannon.admin.others
#goathorncannon.reload - will always check permission
use-permissions: true
admin-use-permissions: true

#Determines whether cannon can damage players
damage-players: false
damage-players-admin: false

#Determines whether cannon can damage entities
damage-entities: false
damage-entities-admin: false

#Determines how much damage a cannon can do (in whole numbers):
damage-amount: 0
damage-amount-admin: 0

#Determines the crit rate in percents. Crits do double damage.
crit-rate: 10
crit-rate-admin: 20

#Highlights players affected by the horn (spectral effect):
highlight-players: false
highlight-players-admin: true

#Highlights entities affected by the horn (spectral effect):
highlight-entities: false
highlight-entities-admin: true

#Determines the block range forward for the cannon:
range: 3
range-admin: 5

#Determines the max launch distance of the entities in front of the player:
max-launch-distance: 10
max-launch-distance-admin: 15

#Determines whether a player can launch themselves by looking at the ground
launch-owner: true
launch-owner-admin: true

#Determines the max launch distance of the player launching themselves:
max-launch-owner: 1
max-launch-owner-admin: 2

#Sets the cooldown length for the cannon in seconds. If 0, uses the default horn cooldown (7 seconds).
cooldown-length: 3
cooldown-length-admin: 3

#Sets the CustomModelData tag for the cannon
custom-model-data: 350000
custom-model-data-admin: 350001

#Sets the sound file to play when the cannon is used. Must be an in-game sound.
fire-sound: ENTITY_FIREWORK_ROCKET_BLAST
fire-sound-admin: ENTITY_FIREWORK_ROCKET_LARGE_BLAST

#Choose whether to keep the original horn sound when using cannon.
keep-horn-sound: false
keep-horn-sound-admin: false